name: Newman API Tests

on:
  workflow_dispatch:

jobs:
  test:
    environment: staging
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Ensures the repository is checked out

      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: "Install newman"
        run: "npm install -g newman"

      - name: "Install newman reporter"
        run: "npm install -g newman-reporter-htmlextra"

      - name: "Run tests"
        run: |
          newman run ./tests/NewmanDemo.postman_collection.json \
            -e ./tests/ReqResDev.postman_environment.json \
            -r htmlextra \
            --reporter-htmlextra-export ./runreport.html \
            --reporter-htmlextra-darkTheme
